# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - jaco_arm_controller
    - hand_controller

  jaco_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - j2n6s200_joint_1
      - j2n6s200_joint_2
      - j2n6s200_joint_3
      - j2n6s200_joint_4
      - j2n6s200_joint_5
      - j2n6s200_joint_6
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - j2n6s200_joint_finger_1
      - j2n6s200_joint_finger_2
    action_ns: gripper_cmd
    default: true